### ISSUE TITLE
Export Rates Colours

### ISSUE THREAD

**Issue by MycroftVonLipwig** [lozzd/octopus-energy-rates-card#3]
Thank you for converting this card, its working well for Import Prices on Agile.

Would it be possible to have an inverted colour scheme for Export Agile rates? 
I.e. Red When low, Orange when Average and Green when High (Blue when greater than import cost or above a limit of say 50p)

I have added the card to my export MPAN and it does work as expected but the colours are the only thing that could be tweaked if its reasonably trivial.

Thanks again!

![Export](https://user-images.githubusercontent.com/11655424/216282771-546806ee-58fa-4b84-80e2-fe95ff009fd7.jpg)

**Comment by lozzd** [comment]
Ah yeah that makes sense. Hoping to move to Agile Export myself soon. 
Anyway, shoud be relatively simple - I'll try and take a look in the next few days.

**Comment by hotnuts21** [comment]
Just to add to this could we possibly have more than 3 levels too, all configurable?

For example I may want to split prices into 4 or 5 levels/ brackets rather than just low medium high. 

Being able to set our own colours for each level or bracket would also help with the issue above, but also for people with visibility difficulties who may need more contrast or just to fit a template. 

Suggestions
Lowlimit  - Bright Blue  - 5p
LowmedLimit  - Green  - 15p
MedLimit - yellow - 25p
HighMesLimit - Orange - 30p
HighLimit - Red - 34p

**Comment by Feridoun** [comment]
Hi sorry if I've missed this, but is there is a sensor that is on when one of the limits are active, red yellow green etc?

**Comment by lozzd** [comment]
This is now in v0.1.3! 
@hotnuts21 I don't have any plans to do this just yet but please feel free to open a new issue for this so it can be tracked separately
